"use client";

import Link from "next/link";
import { useState } from "react";
import { api } from "@/lib/api";
import { Field, PageHeader, SelectField } from "@/components/AdminUI";

export default function NewMovie(){
 const [f,setF]=useState({title:"",description:"",posterUrl:"",trailerUrl:"",duration:"",genreIds:"",screenId:"",startTime:""});const [error,setError]=useState("");const [loading,setLoading]=useState(false);
 function u(k,v){setF(x=>({...x,[k]:v}))}
 async function submit(e){e.preventDefault();setError("");setLoading(true);try{await api.createMovie({title:f.title,description:f.description,posterUrl:f.posterUrl||undefined,trailerUrl:f.trailerUrl||undefined,duration:Number(f.duration),genreIds:f.genreIds.split(",").map(Number).filter(Boolean),showTimes:[{screenId:Number(f.screenId),startTime:new Date(f.startTime).toISOString()}]});window.location.href="/admin/movies"}catch(e){setError(e.message)}finally{setLoading(false)}}
 return <div><PageHeader title="Add movie" description="The backend requires at least one showtime when creating a movie."/><form onSubmit={submit} className="max-w-5xl space-y-6"><section className="rounded-2xl border border-white/[.06] bg-panel p-5 sm:p-7"><div className="grid gap-5 md:grid-cols-2"><Field label="Title" value={f.title} onChange={e=>u("title",e.target.value)} required placeholder="Dune: Part Two"/><Field label="Duration (minutes)" type="number" value={f.duration} onChange={e=>u("duration",e.target.value)} required placeholder="166"/><div className="md:col-span-2"><label className="block"><span className="mb-2 block text-sm text-zinc-400">Description</span><textarea value={f.description} onChange={e=>u("description",e.target.value)} required rows={5} className="w-full rounded-xl border border-white/[.08] bg-white/[.025] p-3 text-sm outline-none focus:border-red-600/60"/></label></div><Field label="Poster URL" value={f.posterUrl} onChange={e=>u("posterUrl",e.target.value)} placeholder="https://..."/><Field label="Trailer URL" value={f.trailerUrl} onChange={e=>u("trailerUrl",e.target.value)} placeholder="https://..."/><Field label="Genre IDs (comma separated)" value={f.genreIds} onChange={e=>u("genreIds",e.target.value)} required placeholder="1,2"/><div className="md:col-span-2 rounded-xl border border-amber-900/30 bg-amber-950/10 p-3 text-xs leading-5 text-amber-300">Your supplied API does not expose a GET /genres endpoint, so the frontend cannot safely invent a genre selector. Enter existing genre IDs from your database.</div></div></section>
 <section className="rounded-2xl border border-white/[.06] bg-panel p-5 sm:p-7"><h2 className="font-semibold">First showtime</h2><p className="mt-1 text-sm text-zinc-700">Movie creation requires a non-empty showTimes array.</p><div className="mt-5 grid gap-5 md:grid-cols-2"><Field label="Screen ID" type="number" value={f.screenId} onChange={e=>u("screenId",e.target.value)} required placeholder="1"/><Field label="Start time" type="datetime-local" value={f.startTime} onChange={e=>u("startTime",e.target.value)} required/></div></section>
 {error&&<div className="rounded-xl border border-red-900/40 bg-red-950/20 p-3 text-sm text-red-300">{error}</div>}<div className="flex justify-end gap-3"><Link href="/admin/movies" className="rounded-xl border border-white/[.08] px-5 py-3 text-sm text-zinc-500">Cancel</Link><button disabled={loading} className="rounded-xl bg-red-600 px-5 py-3 text-sm font-semibold disabled:opacity-50">{loading?"Creating...":"Create movie"}</button></div></form></div>
}
